env:
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 9
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - off
  no-undef:
    - off
