defaults: &defaults
  docker:
    - image: circleci/node:8.0
version: 2
jobs:
  checkout:
    steps:
      - checkout
      - run:
        name: Checkout dependencies
        command: npm install
  lint:
    steps:
      - attach_workspace:
      - run:
          name: Lint TypeScript code
          command: npm run-script lint

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - lint:
        requires:
            - checkout
