defaults: &defaults
  docker:
    - image: circleci/node:8.0
version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout
      - run:
        name: Checkout dependencies
        command: npm install
      - persist_to_workspace:
        root: ~/repo

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build TypeScript code
          command: npm build

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
      - run:
          name: Lint TypeScript code
          command: npm run-script lint

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - lint:
        requires:
            - checkout
      - build:
          requires:
            - lint
