version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - run:
        name: Checkout dependencies
        command: npm install
  lint:
      steps:
        - attach_workspace:
        - run:
            name: Lint TypeScript code
            command: npm run-script lint
